#%RAML 1.0 Api
title: filterize.net
version: v1
baseUri: https://api.filterize.net/v1
mediaType: application/json

securitySchemes:
  oauth_2_0: !include securitySchemes/oauth_2_0.raml

securedBy: [oauth_2_0]

types:
  href: string

/{user_or_business}:
  displayName: User or business
  uriParameters:
    user_or_business:
      type: string
      enum:
        - user
        - business
  /{id}:
    displayName: A specific user
    get:
      description: Get information about the user object.
    /app:
      get:
      /{client_id}:
        delete:
        get:
        post:
          body:
            application/json:
        /{name}:
          get:
          delete:
          post:
            body:
              application/json:
          /{value}:
            get:
            delete:
            post:
              body:
                application/json:
    /filters:
      get:
      post:
        body:
          application/json:
      /{guid}:
        get:
        put:
          body:
            application/json:
    /tags:
      get:
      post:
        body:
          application/json:

/user:
  get:
    displayName: Get basic information about the current user
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              first_name: string
              last_name: string
              profile:
                type: object
                properties:
                  id: integer
              address: string
              city: string
              state: string
              zip_code: string
              country: string
              company: string
              email: string
              phone: string
              user:
                type: object
                properties:
                  id: integer
                  href: href
              business:
                type: object
                properties:
                  id: integer
                  href: href
                  admin: boolean
  put:
    displayName: Update user meta information.
    body:
      application/json:
        properties:
          first_name?: string
          last_name?: string
          address?: string
          city?: string
          state?: string
          zip_code?: string
          country?: string
          company?: string
          email?: string
          password?: string
          phone?: string
