#%RAML 1.0 OAuth2SecurityScheme
description:  All API calls are protected by OAuth2
type: OAuth 2.0
describedBy:
  headers:
    Authorization:
      description: |
        Used to send a valid OAuth 2 access token. Do not use with the "access_token" query string parameter.
      type: string
  queryParameters:
    access_token:
      description: |
         Used to send a valid OAuth 2 access token. Do not use together with the "Authorization" header
      type: string
settings:
  authorizationUri: https://app.filterize.net/oauth2/authorize
  accessTokenUri: https://app.filterize.net/oauth2/token
  authorizationGrants: [ implicit, authorization_code ]
